FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Add the --host flag to listen on all interfaces
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]