version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom nginx configuration
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env  # Reference the root .env file
    environment:
      - VITE_API_URL=http://localhost/api
    volumes:
      - ./frontend:/app  # Mount the frontend directory
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "5173:5173"  # Expose the frontend port

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env  # Reference the root .env file
    environment:
      - PORT=5174
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "5174:5174"  # Expose the backend port