version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network    # Added network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    environment:
      - PORT=5174
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "5174:5174"
    networks:
      - app-network    # Added network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    environment:
      - VITE_API_URL=http://nginx/api
      - NODE_ENV=development
    ports:
      - "5173:5173"
    networks:
      - app-network    # Added network

networks:    # Added networks section
  app-network:
    driver: bridge